# Generated by Django 5.1.2 on 2024-10-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
