# Generated by Django 5.1.2 on 2024-10-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0004_remove_usuarios_contraseñahash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(blank=True, db_column='Username', max_length=100, null=True),
        ),
    ]
