# Generated by Django 5.1.2 on 2024-10-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estilist_backend', '0006_alter_usuarios_idlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
